export const cards = [
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
        {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    },
    {
        'Thumbnail': './assets/thumbnails/thumbnail1.png',
        'TempoDeVideo': '00:00',
        'IconeCanal': './assets/logos/logo1.png',
        'Titulo': 'Tem um titulo aqui',
        'NomeCanal': 'Tem um nome aqui',
        'Vizualizações': 'Tem muitas vizualizações aqui',
        'TempoDePublicação': '3 Meses',
    }
];
